server:
  port: 8090
  tomcat:
    accept-count: 2000
    max-threads: 800
    min-spare-threads: 100
    accesslog:
      enabled: true
      directory: /var/www/miaosha/tomcat
      pattern: "%h %l %u %t '%r' %s %b %D"

#  mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://127.0.0.1:3306/miaosha
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    host: 192.168.29.129
    port: 6379
    database: 10
    # jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 20

mq:
  nameserver:
    addr: 47.119.122.103:9876
  topicname: stock


